#define V y[0]
#define Cai y[1]
#define CaSR y[2]
#define m y[3]
#define h y[4]
#define j y[5]
#define xr1 y[6]
#define xr2 y[7]
#define xs y[8]
#define r y[9]
#define s y[10]
#define d y[11]
#define f y[12]
#define f_ca y[13]
#define g y[14]
#define xf y[15]
#define dCaT y[16]
#define fCaT y[17]
 
#define dVdt dy[0]
#define dCaidt dy[1]
#define dCaSRdt dy[2]
#define dmdt dy[3]
#define dhdt dy[4]
#define djdt dy[5]
#define dxr1dt dy[6]
#define dxr2dt dy[7]
#define dxsdt dy[8]
#define drdt dy[9]
#define dsdt dy[10]
#define dddt dy[11]
#define dfdt dy[12]
#define df_cadt dy[13]
#define dgdt dy[14]
#define dxfdt dy[15]
#define ddCaTdt dy[16]
#define dfCaTdt dy[17]

#define RTONF odeParams->RTONF
#define R odeParams->R
#define T odeParams->T
#define F odeParams->F
#define Ek odeParams->Ek
#define Ena odeParams->Ena
#define Eks odeParams->Eks
#define Eca odeParams->Eca
#define Ef odeParams->Ef
#define alpha_K1 odeParams->alpha_K1
#define beta_K1 odeParams->beta_K1
#define x_K1_inf odeParams->x_K1_inf
#define shift odeParams->shift
#define Ko odeParams->Ko
#define Nao odeParams->Nao
#define Cao odeParams->Cao

#define INa odeParams->INa
#define ICaL odeParams->ICaL
#define Ito odeParams->Ito
#define IKr odeParams->IKr
#define IKs odeParams->IKs
#define IK1 odeParams->IK1
#define INaCa odeParams->INaCa
#define INaK odeParams->INaK
#define IpCa odeParams->IpCa
#define IpK odeParams->IpK
#define IbNa odeParams->IbNa
#define IbCa odeParams->IbCa
#define Istim odeParams->Istim
#define ICaT odeParams->ICaT
#define If   odeParams->If
#define Itotal odeParams->Itotal
#define Ileak odeParams->Ileak
#define Iup odeParams->Iup
#define Irel odeParams->Irel
#define CaCurrent odeParams->CaCurrent
#define CaSRCurrent odeParams->CaSRCurrent
#define Caibufc odeParams->Caibufc
#define CaSRbufsr odeParams->CaSRbufsr
#define Nai odeParams->Nai
#define Ki odeParams->Ki
#define Vc odeParams->Vc
#define Vsr odeParams->Vsr
#define Bufc odeParams->Bufc
#define Kbufc odeParams->Kbufc
#define Bufsr odeParams->Bufsr
#define Kbufsr odeParams->Kbufsr
#define Vmaxup odeParams->Vmaxup
#define Kup odeParams->Kup
#define CAP odeParams->CAP
#define GNa odeParams->GNa
#define GCaL odeParams->GCaL
#define Gto odeParams->Gto
#define Gkr odeParams->Gkr
#define pKNa odeParams->pKNa
#define Gks  odeParams->Gks 
#define GK1 odeParams->GK1
#define knaca odeParams->knaca
#define KmNai odeParams->KmNai
#define KmCa odeParams->KmCa
#define ksat odeParams->ksat
#define n odeParams->n
#define KmK odeParams->KmK
#define KmNa odeParams->KmNa
#define knak odeParams->knak
#define GpCa odeParams->GpCa
#define KpCa odeParams->KpCa
#define GpK odeParams->GpK
#define GbNa odeParams->GbNa
#define GbCa odeParams->GbCa
#define alpha odeParams->alpha
#define Vleak odeParams->Vleak
#define L_0 odeParams->L_0
#define Q odeParams->Q
#define GCaT odeParams->GCaT
#define Gf odeParams->Gf
#define Grel odeParams->Grel
#define arel odeParams->arel
#define brel odeParams->brel
#define crel odeParams->crel

#define alpha_m  odeParams->alpha_m
#define beta_m  odeParams->beta_m
#define tau_m  odeParams->tau_m
#define m_inf  odeParams->m_inf
#define alpha_h  odeParams->alpha_h
#define beta_h  odeParams->beta_h
#define tau_h  odeParams->tau_h
#define h_inf  odeParams->h_inf
#define alpha_j  odeParams->alpha_j
#define beta_j  odeParams->beta_j
#define tau_j  odeParams->tau_j
#define j_inf  odeParams->j_inf
#define alpha_d  odeParams->alpha_d
#define beta_d  odeParams->beta_d
#define gamma_d  odeParams->gamma_d
#define tau_d  odeParams->tau_d
#define d_inf  odeParams->d_inf
#define f_inf  odeParams->f_inf
#define tau_f  odeParams->tau_f
#define g_inf  odeParams->g_inf
#define tau_g  odeParams->tau_g
#define constg  odeParams->constg
#define f_ca_inf  odeParams->f_ca_inf
#define tau_f_ca  odeParams->tau_f_ca
#define constf_ca  odeParams->constf_ca
#define r_inf  odeParams->r_inf
#define tau_r  odeParams->tau_r
#define s_inf  odeParams->s_inf
#define tau_s  odeParams->tau_s
#define alpha_xs  odeParams->alpha_xs
#define beta_xs  odeParams->beta_xs
#define xs_inf  odeParams->xs_inf
#define tau_xs  odeParams->tau_xs
#define alpha_xr1  odeParams->alpha_xr1
#define beta_xr1  odeParams->beta_xr1
#define xr1_inf  odeParams->xr1_inf
#define tau_xr1  odeParams->tau_xr1
#define v_half odeParams->v_half
#define alpha_xr2  odeParams->alpha_xr2
#define beta_xr2  odeParams->beta_xr2
#define xr2_inf  odeParams->xr2_inf
#define tau_xr2  odeParams->tau_xr2
#define xf_inf  odeParams->xf_inf
#define tau_xf  odeParams->tau_xf
#define dCaT_inf  odeParams->dCaT_inf
#define tau_dCaT  odeParams->tau_dCaT
#define fCaT_inf  odeParams->fCaT_inf
#define tau_fCaT  odeParams->tau_fCaT

#define RaINa odeParams->RaINa
#define myCoefTauH odeParams->myCoefTauH
#define myCoefTauJ odeParams->myCoefTauJ
#define RaICaL odeParams->RaICaL
#define Vh_dCa odeParams->Vh_dCa
#define kCa odeParams->kCa
#define ampICaLDinf odeParams->ampICaLDinf
#define KtaufCa odeParams->KtaufCa
#define myVhfCaL odeParams->myVhfCaL
#define myKfCaL odeParams->myKfCaL
#define ampICaLFinf odeParams->ampICaLFinf
#define myKtauF odeParams->myKtauF
#define myTauFShift odeParams->myTauFShift
#define myShiftFCaInf odeParams->myShiftFCaInf
#define Vth_ICaL odeParams->Vth_ICaL
#define RaICaT odeParams->RaICaT
#define RaINaCa odeParams->RaINaCa
#define alfa odeParams->alfa
#define RaINaK odeParams->RaINaK
#define RaIK1 odeParams->RaIK1
#define myShiftK1 odeParams->myShiftK1
#define RaIKr odeParams->RaIKr
#define poffi  odeParams->poffi 
#define mySlope odeParams->mySlope
#define myShift odeParams->myShift
#define RaIKs odeParams->RaIKs
#define RaIto odeParams->RaIto
#define myShiftItoR odeParams->myShiftItoR
#define mySlopeItoR odeParams->mySlopeItoR
#define myShiftItoS odeParams->myShiftItoS
#define mySlopeItoS odeParams->mySlopeItoS
#define myConstTauR odeParams->myConstTauR
#define myConstTauS odeParams->myConstTauS
#define RaIup odeParams->RaIup
#define RaIrel odeParams->RaIrel
#define RaIleak odeParams->RaIleak
#define RaIf odeParams->RaIf
#define Rax0 odeParams->Rax0
#define Radx odeParams->Radx
#define myIfconst odeParams->myIfconst
#define RaCm odeParams->RaCm
#define RaICap odeParams->RaICap
#define RaIKp odeParams->RaIKp
#define RaIback odeParams->RaIback

#define Nao_naca odeParams->Nao_naca
#define capacitance odeParams->capacitance
#define svolt odeParams->svolt
#define Vh_h odeParams->Vh_h
#define k_h odeParams->k_h
#define Gnamax odeParams->Gnamax
#define GICaT  odeParams->GICaT 
#define GItoepi odeParams->GItoepi
#define GItoendo odeParams->GItoendo
#define GItoMcell odeParams->GItoMcell
#define GKsepi    odeParams->GKsepi   
#define GKsendo   odeParams->GKsendo  
#define GKsMcell  odeParams->GKsMcell 
#define GKr odeParams->GKr
#define gK1max odeParams->gK1max
#define Q odeParams->Q
#define L0 odeParams->L0
#define Kc odeParams->Kc
#define Ka odeParams->Ka
#define kpca odeParams->kpca

#define xr1o odeParams->xr1o;
#define xr2o odeParams->xr2o;
#define x0 odeParams->x0;
#define dx odeParams->dx;

